raw_data:
  train_data: "data/raw/train.csv"
  test_data: "data/raw/test.csv"

interim_data:
  train_data: "data/interim/train.csv"
  val_data: "data/interim/val.csv"


features:
  target_column: "trip_duration"

plots:
  target_distribution: "reports/figures/target_distribution.png"


main_dir: "./"