stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    - data/raw/train.csv
    params:
    - make_dataset.test_size
    - make_dataset.random_state
    outs:
    - data/interim/train.csv
    - data/interim/val.csv
  
  modify_features:
    cmd: python ./src/features/modify_features.py data/interim/train.csv data/interim/val.csv data/raw/test.csv
    deps:
      - ./src/features/modify_features.py
      - ./data/interim/train.csv
      - ./data/interim/val.csv
      - ./data/raw/test.csv
    outs:
      - ./data/processed/transformations
